#!/bin/sh

test a"$SJ_DIR"b != ab || { echo SJ_DIR is not defined; exit 1; }
cd "$SJ_DIR" || { echo cannot cd to "$SJ_DIR"; exit 1; }

outfiles=`find . -name out`
tail -f -n5 $outfiles &
tailpid=$!
trap "kill $tailpid; exit" HUP INT ABRT TERM
while true; do
	new_outfiles=`find . -name out`
	if [ "$outfiles" != "$new_outfiles" ] ; then
		outfiles="$new_outfiles"
		kill $tailpid
		printf '\a\n'
		tail -f -n5 $outfiles &
		tailpid=$!
		trap "kill $tailpid; exit" HUP INT ABRT TERM
	fi
	sleep 5
done
kill $tailpid

#tail -f -n5 $outfiles | while IFS= read -r line; do
#	printf '%s\a\n' "$line"
#done &
