#!/bin/sh
[ "$DEBUG" ] && set -x

usage="usage: $(basename $0) [-d <directory>]
Run this command with watch for extra functionality."

while [ "$1" ]; do
	case "$1" in
		-d) SJ_DIR="$2"; shift;;
		*)  printf "$(basename $0): invalid option $1\n$usage\n"; exit 1;;
	esac
	shift
done

[ "$SJ_DIR" ] || { echo SJ_DIR is not defined; exit 1; }
cd "$SJ_DIR" || { echo cannot cd to "$SJ_DIR"; exit 1; }
pgrep presenced >/dev/null || { echo no presenced; exit 1; }

status="$(find . -maxdepth 2 -name status)"
if [ "$status" ]; then
	echo Online Buddies
	echo --------------
	egrep '.+' $status | sed 's|^\./||g' | sed 's|/status:|:\t|g'
else
	echo No status files found
	exit 1
fi

echo
echo Offline Buddies
echo ---------------
for f in *; do
	if [ -d "$f" ]; then
		if [ ! -s "$f"/status ]; then
			echo "$f"
		fi
	fi
done
