#!/bin/sh
# run from watch

[ "$SJ_DIR" = "" ] && { echo SJ_DIR is not defined; exit 1; }
cd "$SJ_DIR" || { echo cannot cd to "$SJ_DIR"; exit 1; }
pgrep presenced >/dev/null || { echo no presenced; exit 1; }

status="$(find . -name status)"
if test -n "$status"; then
	echo Online Buddies
	echo --------------
	egrep '.+' $status | sed 's|^\./||g' | sed 's|/status:|:\t|g'
else
	echo No status files found
	exit 1
fi

echo
echo Offline Buddies
echo ---------------
for f in *; do
	if test -d "$f"; then
		if test ! -s "$f"/status; then
			echo "$f"
		fi
	fi
done
